import { motion } from 'framer-motion'
import { Scale, AlertTriangle, FileText, Users, Shield, Bot, Gavel, CreditCard } from 'lucide-react'

export function TermsOfServicePage() {
  const fadeInUp = {
    initial: { opacity: 0, y: 20 },
    animate: { opacity: 1, y: 0 },
    transition: { duration: 0.6 }
  }

  const sections = [
    {
      id: "acceptance",
      title: "Acceptance of Terms",
      icon: <FileText className="w-5 h-5" />,
      content: [
        {
          subtitle: "Agreement to Terms",
          text: "By accessing or using ChefoodAI™ services, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using our services."
        },
        {
          subtitle: "Capacity to Contract",
          text: "You represent that you are at least 18 years old and have the legal capacity to enter into this agreement. If you are using our services on behalf of an organization, you represent that you have authority to bind that organization."
        },
        {
          subtitle: "Changes to Terms",
          text: "We reserve the right to modify these terms at any time. Changes will be effective immediately upon posting. Your continued use of our services constitutes acceptance of the modified terms."
        }
      ]
    },
    {
      id: "services",
      title: "Description of Services",
      icon: <Bot className="w-5 h-5" />,
      content: [
        {
          subtitle: "AI-Powered Recipe Generation",
          text: "ChefoodAI™ provides artificial intelligence-powered recipe generation, meal planning, and cooking assistance. Our AI systems create personalized content based on your preferences and dietary requirements."
        },
        {
          subtitle: "Service Availability",
          text: "We strive to provide continuous service availability but do not guarantee uninterrupted access. Services may be temporarily unavailable due to maintenance, updates, or technical issues."
        },
        {
          subtitle: "Beta Features",
          text: "Some features may be provided as beta or experimental versions. These features are provided 'as is' and may contain bugs or be subject to significant changes."
        },
        {
          subtitle: "Third-Party Integrations",
          text: "Our services may integrate with third-party platforms and services. We are not responsible for the availability, accuracy, or functionality of third-party services."
        }
      ]
    },
    {
      id: "user-responsibilities",
      title: "User Responsibilities & Conduct",
      icon: <Users className="w-5 h-5" />,
      content: [
        {
          subtitle: "Account Security",
          text: "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately of any unauthorized access."
        },
        {
          subtitle: "Acceptable Use",
          text: "You may not use our services for any unlawful purpose, to transmit harmful content, to impersonate others, or to interfere with our systems or other users' experience."
        },
        {
          subtitle: "Content Accuracy",
          text: "While we strive for accuracy, you acknowledge that AI-generated recipes and meal plans are suggestions only. You are responsible for verifying ingredient safety, nutritional accuracy, and suitability for your dietary needs."
        },
        {
          subtitle: "Feedback and Ideas",
          text: "Any feedback, suggestions, or ideas you provide may be used by us without restriction or compensation to improve our services."
        }
      ]
    },
    {
      id: "ai-disclaimers",
      title: "AI Services & Disclaimers",
      icon: <AlertTriangle className="w-5 h-5" />,
      content: [
        {
          subtitle: "AI-Generated Content",
          text: "Content generated by our AI systems is created algorithmically and may not always be accurate, appropriate, or suitable for your specific needs. Always use your judgment and consult professionals when necessary."
        },
        {
          subtitle: "Nutritional Information",
          text: "Nutritional information provided is approximate and for informational purposes only. For medical dietary needs, consult healthcare professionals. We are not liable for any health impacts from following our recommendations."
        },
        {
          subtitle: "Allergen Warnings",
          text: "While we attempt to identify common allergens, our AI may not catch all potential allergens or cross-contamination risks. Always verify ingredients if you have food allergies."
        },
        {
          subtitle: "Cultural Sensitivity",
          text: "We strive to create culturally appropriate content, but AI-generated recipes may not always reflect authentic cultural practices or dietary restrictions."
        },
        {
          subtitle: "No Medical Advice",
          text: "Our services do not provide medical advice. Consult healthcare professionals for medical dietary needs, weight management, or health-related cooking decisions."
        }
      ]
    },
    {
      id: "intellectual-property",
      title: "Intellectual Property Rights",
      icon: <Shield className="w-5 h-5" />,
      content: [
        {
          subtitle: "Our Intellectual Property",
          text: "ChefoodAI™'s technology, algorithms, software, trademarks, and other intellectual property are owned by us and protected by applicable laws. You may not copy, modify, or reverse engineer our systems."
        },
        {
          subtitle: "User-Generated Content",
          text: "You retain ownership of content you create, but grant us a license to use, modify, and distribute it as necessary to provide our services. You represent that you own or have rights to any content you upload."
        },
        {
          subtitle: "AI-Generated Content",
          text: "Recipes and content generated by our AI systems are provided under a creative commons license for personal use. Commercial use requires explicit permission."
        },
        {
          subtitle: "Copyright Respect",
          text: "Respect others' intellectual property rights. Do not upload copyrighted recipes or content without permission. We will respond to valid DMCA takedown notices."
        }
      ]
    },
    {
      id: "privacy",
      title: "Privacy & Data Protection",
      icon: <Shield className="w-5 h-5" />,
      content: [
        {
          subtitle: "Privacy Policy",
          text: "Our collection and use of personal information is governed by our Privacy Policy, which is incorporated into these terms by reference."
        },
        {
          subtitle: "Data Processing",
          text: "By using our services, you consent to the processing of your data as described in our Privacy Policy, including for AI model training and service improvement."
        },
        {
          subtitle: "Data Security",
          text: "We implement reasonable security measures to protect your data, but cannot guarantee absolute security. You use our services at your own risk regarding data security."
        },
        {
          subtitle: "International Data Transfers",
          text: "Your data may be processed in countries other than your own. We ensure appropriate safeguards are in place for international data transfers."
        }
      ]
    },
    {
      id: "billing",
      title: "Billing & Payments",
      icon: <CreditCard className="w-5 h-5" />,
      content: [
        {
          subtitle: "Subscription Plans",
          text: "Paid plans are billed in advance on a monthly or annual basis. Billing cycles begin on the date you first subscribe to a paid plan."
        },
        {
          subtitle: "Payment Methods",
          text: "We accept major credit cards and other payment methods as displayed during checkout. You authorize us to charge your payment method for all fees incurred."
        },
        {
          subtitle: "Refund Policy",
          text: "Refunds are generally not provided for services already rendered. However, we may provide refunds at our discretion for technical issues or billing errors."
        },
        {
          subtitle: "Price Changes",
          text: "We may change subscription prices with 30 days' advance notice. Price changes will not affect your current billing cycle but will apply to subsequent renewals."
        },
        {
          subtitle: "Cancellation",
          text: "You may cancel your subscription at any time. Cancellation will take effect at the end of your current billing period. No refunds will be provided for partial periods."
        }
      ]
    },
    {
      id: "disclaimers",
      title: "Disclaimers & Limitations",
      icon: <AlertTriangle className="w-5 h-5" />,
      content: [
        {
          subtitle: "Service Warranty",
          text: "Our services are provided 'as is' without warranties of any kind. We disclaim all warranties, express or implied, including merchantability, fitness for a particular purpose, and non-infringement."
        },
        {
          subtitle: "Limitation of Liability",
          text: "To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including lost profits or data."
        },
        {
          subtitle: "Maximum Liability",
          text: "Our total liability to you for any claims related to our services shall not exceed the amount you paid us in the 12 months preceding the claim."
        },
        {
          subtitle: "Food Safety",
          text: "We are not responsible for food safety, cooking results, or any health issues that may arise from following AI-generated recipes or meal plans."
        }
      ]
    },
    {
      id: "termination",
      title: "Termination",
      icon: <Gavel className="w-5 h-5" />,
      content: [
        {
          subtitle: "Termination by You",
          text: "You may terminate your account at any time by contacting us or using account deletion features. Termination does not entitle you to any refunds."
        },
        {
          subtitle: "Termination by Us",
          text: "We may suspend or terminate your account for violation of these terms, illegal activity, or other reasons at our discretion, with or without notice."
        },
        {
          subtitle: "Effect of Termination",
          text: "Upon termination, your access to our services will cease, and we may delete your account data according to our data retention policies."
        },
        {
          subtitle: "Survival of Terms",
          text: "Provisions regarding intellectual property, disclaimers, limitations of liability, and other terms by their nature shall survive termination."
        }
      ]
    },
    {
      id: "general",
      title: "General Provisions",
      icon: <Scale className="w-5 h-5" />,
      content: [
        {
          subtitle: "Governing Law",
          text: "These terms are governed by the laws of California, United States, without regard to conflict of law principles."
        },
        {
          subtitle: "Dispute Resolution",
          text: "Any disputes arising from these terms or our services shall be resolved through binding arbitration in San Francisco, California, rather than in court."
        },
        {
          subtitle: "Severability",
          text: "If any provision of these terms is found to be unenforceable, the remaining provisions will remain in full force and effect."
        },
        {
          subtitle: "Entire Agreement",
          text: "These terms, along with our Privacy Policy, constitute the entire agreement between you and ChefoodAI™ regarding our services."
        },
        {
          subtitle: "Contact Information",
          text: "For questions about these terms, contact us at legal@chefoodai.com or use our contact form."
        }
      ]
    }
  ]

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-white">
      {/* Hero Section */}
      <section className="relative pt-44 md:pt-52 pb-20 px-4 sm:px-6 lg:px-8 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-blue-500/10 to-purple-600/10" />
        <motion.div 
          className="relative max-w-4xl mx-auto text-center"
          {...fadeInUp}
        >
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="inline-flex items-center justify-center w-20 h-20 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full mb-8 shadow-xl"
          >
            <Scale className="w-10 h-10 text-white" />
          </motion.div>

          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
            Terms of 
            <span className="bg-gradient-to-r from-blue-500 to-purple-600 bg-clip-text text-transparent"> Service</span>
          </h1>
          
          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto leading-relaxed">
            These terms govern your use of ChefoodAI™ services. Please read them carefully as they contain 
            important information about your rights and obligations.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center text-sm text-gray-500">
            <span>Last updated: January 10, 2025</span>
            <span className="hidden sm:inline">•</span>
            <span>Effective date: January 1, 2025</span>
          </div>
        </motion.div>
      </section>

      {/* Key Points Summary */}
      <section className="py-12 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-center mb-8"
          >
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Key Points Summary</h2>
            <p className="text-gray-600">Important highlights from our terms of service</p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="bg-blue-50 rounded-xl p-6 text-center"
            >
              <Bot className="w-8 h-8 text-blue-600 mx-auto mb-3" />
              <h3 className="font-semibold text-gray-900 mb-2">AI Services</h3>
              <p className="text-sm text-gray-600">AI-generated content is provided as suggestions only</p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="bg-green-50 rounded-xl p-6 text-center"
            >
              <Shield className="w-8 h-8 text-green-600 mx-auto mb-3" />
              <h3 className="font-semibold text-gray-900 mb-2">Privacy Protection</h3>
              <p className="text-sm text-gray-600">Your data is protected according to our Privacy Policy</p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="bg-yellow-50 rounded-xl p-6 text-center"
            >
              <AlertTriangle className="w-8 h-8 text-yellow-600 mx-auto mb-3" />
              <h3 className="font-semibold text-gray-900 mb-2">Food Safety</h3>
              <p className="text-sm text-gray-600">Always verify ingredients and cooking safety</p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.4 }}
              className="bg-purple-50 rounded-xl p-6 text-center"
            >
              <CreditCard className="w-8 h-8 text-purple-600 mx-auto mb-3" />
              <h3 className="font-semibold text-gray-900 mb-2">Billing</h3>
              <p className="text-sm text-gray-600">Subscriptions billed monthly or annually</p>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          {/* Table of Contents */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="bg-gray-50 rounded-xl p-6 mb-12"
          >
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Table of Contents</h2>
            <div className="grid md:grid-cols-2 gap-3">
              {sections.map((section, index) => (
                <a
                  key={section.id}
                  href={`#${section.id}`}
                  className="flex items-center space-x-3 text-blue-600 hover:text-blue-700 transition-colors"
                >
                  {section.icon}
                  <span className="text-sm font-medium">{section.title}</span>
                </a>
              ))}
            </div>
          </motion.div>

          {/* Terms Sections */}
          <div className="space-y-16">
            {sections.map((section, sectionIndex) => (
              <motion.div
                key={section.id}
                id={section.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: sectionIndex * 0.1 }}
                className="scroll-mt-20"
              >
                <div className="flex items-center space-x-3 mb-6">
                  <div className="text-blue-600">
                    {section.icon}
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900">
                    {section.title}
                  </h2>
                </div>

                <div className="space-y-6">
                  {section.content.map((item, itemIndex) => (
                    <div key={itemIndex} className="bg-white rounded-lg p-6 shadow-sm border border-gray-100">
                      <h3 className="text-lg font-semibold text-gray-900 mb-3">
                        {item.subtitle}
                      </h3>
                      <p className="text-gray-700 leading-relaxed">
                        {item.text}
                      </p>
                    </div>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>

          {/* Important Notice */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="mt-20 bg-red-50 border-2 border-red-200 rounded-xl p-8"
          >
            <div className="flex items-start space-x-3">
              <AlertTriangle className="w-6 h-6 text-red-600 mt-1 flex-shrink-0" />
              <div>
                <h3 className="text-lg font-semibold text-red-900 mb-2">
                  Important Notice
                </h3>
                <p className="text-red-800 text-sm leading-relaxed mb-4">
                  ChefoodAI™ provides AI-generated cooking content for informational purposes only. 
                  We are not responsible for food safety, nutritional accuracy, or health outcomes. 
                  Always verify ingredients for allergens and consult healthcare professionals for 
                  medical dietary needs.
                </p>
                <p className="text-red-800 text-sm leading-relaxed">
                  By using our services, you acknowledge that you understand these limitations and 
                  agree to use our content responsibly.
                </p>
              </div>
            </div>
          </motion.div>

          {/* Contact Section */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="mt-12 bg-blue-50 rounded-xl p-8 text-center"
          >
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              Questions About These Terms?
            </h2>
            <p className="text-gray-600 mb-6 max-w-2xl mx-auto">
              If you have any questions about these Terms of Service or need clarification 
              on any provisions, please contact our legal team.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a 
                href="mailto:legal@chefoodai.com"
                className="inline-flex items-center justify-center bg-blue-600 text-white px-6 py-3 rounded-lg font-medium hover:bg-blue-700 transition-colors"
              >
                Email Legal Team
              </a>
              <a 
                href="/contact"
                className="inline-flex items-center justify-center border-2 border-blue-600 text-blue-600 px-6 py-3 rounded-lg font-medium hover:bg-blue-50 transition-colors"
              >
                Contact Form
              </a>
            </div>
          </motion.div>

          {/* Legal Notice */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="mt-8 p-6 bg-gray-100 rounded-lg text-sm text-gray-600"
          >
            <p className="mb-2">
              <strong>Document Version:</strong> These Terms of Service are version 2.1, 
              effective January 1, 2025.
            </p>
            <p>
              <strong>Jurisdiction:</strong> These terms are governed by California law and 
              disputes will be resolved in San Francisco, California.
            </p>
          </motion.div>
        </div>
      </section>
    </div>
  )
}
